### PR TITLE
Multilanguage

### PR DESCRIPTION
**Pull request by statnmap**
This allows for translation in custom languages.
- Some texts of the themes where hard-coded in English. These have been moved to a en.toml file in the folder `i18n`. A French translation is also provided.
- To go further, I added flags to link the different translations between them. There is a flag in the side bar and in each post header.
- To add translations of other languages than FR and EN, one should add the flag in the appropriate folder and add lang.toml in the i18n directory.
- I modified the config.toml in the exampleSite to show multilanguage menus.

### CODE REVIEW

**Comment by pacollins** [comment]
Want to get a couple reviews from people to confirm this is working properly before merging.

**Comment by statnmap** [comment]
- I added some corrections to my files to include all the new modifications that you added in the `master` branch.
- I also added a `if Multilingual` test to show flags in sidebar and posts header **only** if the website is multilingual.
- I added the folders `i18n` and `static/flags` in the exampleSite as they are necessary for multilingual website (but also for unique language website).

**Comment by pacollins** [comment]
Cool, I will check this out later today and get back to you. Any chance you have an example site up and running?

**Comment by statnmap** [comment]
Not yet. It's a work in progress. Probably next week. But if you test the `exampleSite`, copy-paste your blog post `creating-a-new-theme.md`and rename it `creating-a-new-theme.fr.md`, you'll see it working. I tested my last commits in this way.  
Here is a snapshot:  
future-imperfect-multilanguage  
and the same in french:
future-imperfect-tr-fr

**Comment by pacollins** [comment]
Yeah, I was just curious if there was a live site since some things are finicky when using the Hugo Localhost Server. It looks great, thanks for putting this together.

**Comment by pacollins** [comment]
I'm not a huge fan of the flag placement. Maybe we should find a spot in the nav bar? Maybe next to the search and make it a drop down menu? And do you think its necessary for it to be within the posts as well? That seems like a redundancy. I figure your intention is to let people know what languages a post is in, but maybe there is a more subtle way for us to achieve that? Just my thoughts after getting mine set up local.

**Comment by pacollins** [comment]
Found an example of what I meant by changing how the flags function, checkout [Amazon's Navbar](https://www.amazon.com/).

**Comment by statnmap** [comment]
I changed the position of the language switcher to the top bar. I was unsure which flags to show, the current translation, or other available. Finally, I made two cases.

1. Smartphone vs desktop
- The `nav main` div has an absolute position when on small devices (<736px) so that flags and search are over the title (on the left).

2. More than 2 languages
- The flag shown is the one of the **current** language.
- On hover, a dropdown menu shows the other languages available.
- If the current page has at least one translation, only flags of translations available will be shown
- If the current page has no translation, the flags of all site languages available are shown and will redirect to the home page of the selected language

3. Two languages
- The flag shown is the one of the **other language** available
- There is **no** dropdown menu because languages available are either the current one or the second one (flag shown)
- If the current page has no translation in the second language, the flag will redirect to the home page of the selected language

**Comment by statnmap** [comment]
I just released the website using this multilanguage theme with a few other minor hacks (tags added in post footers and a few different colours, in my branch `ml`). By the way, articles are not written in French but are supposed translated for hugo (I just copied post.md to post.fr.md):  
<http://marionlouveaux.free.fr>  
While merging the branches, I also remarked there are a few other little things to be translated in the `itemized` and in the `navbar.html`. I think there is something to do with categories links too.  
Work in progress...

**Comment by statnmap** [comment]
I think it is now ok. Categories are also multilingual.
If you plan to add new menus with a fixed name, do not forget to use `{{ i18n "name" }}` and add the translation in `en.toml` and `fr.toml`  

screenshot_multilang

**Comment by pacollins** [comment]
Again, thanks for working on all of this. Honestly will be the biggest update to the theme and increase its usability and accessibility. Once we get this finalized planning this being the v0.30 release.

A few thoughts after looking back through the recent commits

- Don't forget to add the switcher for the mobile navigation (sidebar on the right for smaller screens). Starting at line 46.
- With lacking a translated article, from a UX perspective, should it redirect to the home page, or produce a pop-up/tool tip/404 page that lets the user know that the current page isn't available in that language? It seems odd to redirect to the home page.
- With two languages, would be be best to just keep the drop down so that its more user friendly? 
- Also, we might want to add [fa-angle-down](http://fontawesome.io/icon/angle-down/) and [animation](https://github.com/statnmap/hugo-future-imperfect/blob/b82572edef33d222696f3c8a5934e2da36ad37f2/static/css/main.css#L2089).

Just my thoughts, curious what you are thinking. I think the framework is great, just looking at it from a User Experience perspective.

**Comment by pacollins** [comment]
`config.toml` - Updated to solve merge conflicts with recent PRs. I also solved that it didn't include all of the documentation that was there previously.

Also, I moved the navigation menus under the language, so its:

```
[Languages]
    English
        EnglishInfo
        EnglishNav
    French
        FrenchInfo
        FrenchNav
```
instead of:
```
[Languages]
    English
        EnglishInfo
    French
        FrenchInfo
    EnglishNav
    FrenchNav
```

Thoughts? Seems more intuitive.

Since this could be seen as bloat in `config.toml` for some, I think we need to make it clear via comments what can be removed for the theme to still work as intended for a singular language site. Then, it probably needs to reflect that as well. Possibly something that says `{{ if lt (len .Site.Languages) 2 }} ignore multilingual flags/etc {{end}}`

What do you think?

**Comment by statnmap** [comment]
Flags switcher only appears if the website in `MultiLingual`. If `Languages` do not appear in the config file, the flag won't appear. In the readme file, you could add something like:  

> The `config.toml` file in `exampleSite` proposes menus for a second language (French). If you only have one language for your website, you can remove every `Languages`, `Languages.en` and `Languages.fr` occurrences. Simple `[menu.main]` have to be used instead.

I am working on the other propositions you asked. The redirection to specific 404 page will be simple to do when there are only two languages (with `IsTranslated`). But for more translations, we need to create a specific function to test each Language. I do not really have time to do that now, but I'll do it for the 2 languages website at least, which I guess will cover the majority of user cases, no ?

**Comment by pacollins** [comment]
I appreciate all your work on this and there is no timetable! Haha, I know we are all busy. 

I am working on cleaning up the documentation right now, so I will think of the best way to do that. My guess would be to leave the multilingual menus in the config and then within `readme.md` have a:

> If your site will be a single language, replace everything from `[Languages]` with:
>```
> [menu.main]
>```

Or possibly the inverse might be more applicable for users? Not sure.

I imagine that most users will be limited to two languages, yes. If they needed more, we could cross that bridge when we get there. Do you think 404 is the better option as opposed to a pop-up warning of some kind for the user? I'm curious on your take since that's the one you picked out.

**Comment by statnmap** [comment]
- I don't understand where you want to put the language switcher in the mobile menu. It already appears next to it.
- For a two language website, I put back the dropdown menu. I added a red cross over the flag with missing translation with no redirection. Indeed, you're right, maybe a pop-up would be more interesting as this avoids unnecessary redirection, even if people should understand the red cross. But I am not completely comfortable with javascript.
- My css for the 'fa-angle-down' position and the 'red cross' is not clean, but I am stuck with blocks, inline-blocks, paddings and whatever... Maybe you or someone else would find a cleaner way to show it ?
- By the way, I also translated the 404 page.
- Thinking about documentation, most user will probably have a one-language website, which means that the config.toml example should be presented with one language. But a note can redirect to readme file and hugo documentation (https://gohugo.io/content-management/multilingual/) to explain how to set up multilingual option in the theme.

**Comment by tonyatoms** [comment]
I cannot tell you how happy I am to see this branch and all the work it contains. The original version of the theme is beautiful and meets our needs exactly except for the lack of multilingual support. I spent a few hours trying to do multilingual from scratch yesterday without any joy. I'll test this branch/PR this week. My site is written in English, but we also need to do Spanish and Simplified Chinese.

**Comment by pacollins** [comment]
@statnmap -

1. I think I miss spoke. I purely meant having it translate the menu that appears on mobile.
2. I will pull the latest updates and try to implement something.
3. I will clean this up.
4. Cool 😄 
5. I agree, that might be the best approach

@tonyatoms -

If you could test this and review it, that would be excellent - particularly if you are going tri-lingual. My hope is that we can finalize this and merge by the 13th.

**Comment by tonyatoms** [comment]
@pacollins -
Testing is going well. Even though my implementation isn't quite perfect, It is in production now at: [http://mckinleyparkdevelopmentcouncil.org](http://mckinleyparkdevelopmentcouncil.org). 
I'll more formally review the branch this week.

**Comment by statnmap** [comment]
Sorry, my last commit 300363c was a mistake, I try to revert it

**Comment by pacollins** [comment]
Fixed merge conflicts based on PRs to the master branch.

Leaving this here for review:

I went ahead and took the multilingual version, but this was a conflict where two methods were being taken is the `multilanguage` one the best method, or is the one @mharrend did the best method (assuming you make it `relLangURL`

```
<<<<<<< multilanguage
                                <a href="{{ printf "/%s/%s" $data.Plural $value.Name | urlize | relLangURL }}">{{ $value.Name }}</a>
=======
                                <a href="{{"/" | relURL}}{{ $data.Plural }}/{{ $value.Name | urlize }}">{{ $value.Name }}</a>
>>>>>>> master
```

@statnmap - if you need to do a hard reset back and remove those merge conflict fixes, feel free.

**Comment by statnmap** [comment]
Well, I do not find how to revert it properly. I will remove the lines and provide a new commit. Except it you want to keep the modifications. Indeed, this concerns:

- Add academicons to allow for googlescholar, researchgate and ORCID social icons for researchers
- Simplify the code for category list in the footer of an article
- Add tags along categories in articles footer
- Add tags list template similar to category
- Modify the way article summary is shown (removing titles, list and code blocks)
`ml` is the branch I use on [this website](http://marionlouveaux.free.fr), so that you can see what this changes to the template. If you want me to revert these modifications, I'll do it. If you think it is also interesting, you can keep it.
Sorry, for this mistake...

**Comment by statnmap** [comment]
With:
`<<<<<<< multilanguage
                                <a href="{{ printf "/%s/%s" $data.Plural $value.Name | urlize | relLangURL }}">{{ $value.Name }}</a>
=======
                                <a href="{{"/" | relURL}}{{ $data.Plural }}/{{ $value.Name | urlize }}">{{ $value.Name }}</a>
>>>>>>> master`
I tested different things, but my way already uses relURL, so I dont think the modification of `master` is needed. However, because we are on multilingual, every `relURL` should be `relLangURL` now. Be careful with that.

**Comment by mharrend** [comment]
I would propose to not use 
> {{ printf "/%s/%s" $data.Plural $value.Name | urlize | relLangURL }}

because it can give you some issues with the baseurl if it contains special letters like umlauts ö,ä, and so on.

Better use imho
> {{"/" | relLangURL}}{{ $data.Plural }}/{{ $value.Name | urlize }}

**Comment by pacollins** [comment]
@statnmap - Don't worry about the mistake - they happen. Some of my early pulls/commits here are nasty... if we could revert, that would be ideal just to keep transparency - they might be useful things to add in a separate PR.

[Here](https://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit) is a way to revert it via command line. If you need any more assistance feel free to ask.

> Add academicons to allow for googlescholar, researchgate and ORCID social icons for researchers

I do like this, seems like a natural fit since we lack scholarly social icons.

> Simplify the code for category list in the footer of an article
> Add tags along categories in articles footer
> Add tags list template similar to category

I like all of these, we should have had a tags page, and it makes sense for them to be in the footer (I think, that may be clutter... may need to consider just adding them to the article page).

> Modify the way article summary is shown (removing titles, list and code blocks)

#71 is actually one that I was working on here (I actually see that you found the same article I read, haha).

After reading back through it and reviewing, I am certain that we need to revert and then make separate PRs. It's too far off base from Multilanguage.

On the merge conflict -

I was aware of the `relLangURL` - his PR was on the current master, not on Multilanguage, so that was functional. I was talking more about the `print` portion, but that being said, I think the case he presented above is relevant and recommend we change [that line](https://github.com/statnmap/hugo-future-imperfect/blob/f5c4f6d34949ea07c2a480f7994e2e1c2fef335b/layouts/taxonomy/category.terms.html#L23) to:

```
{{"/" | relLangURL}}{{ $data.Plural }}/{{ $value.Name | urlize }}
```

Thanks to both of you for your contributions.

**Comment by statnmap** [comment]
The revert of the merge is successful. I will propose the reverted modifications in new PR. That makes sense.

Ok for the `print` portion.

**Comment by pacollins** [comment]
Haven't had the chance to really dig into this yet. My plan is to address my styling concerns this weekend.

**Comment by pacollins** [comment]
Updated for all of the `relurl` from #80 / #83.

**Comment by pacollins** [comment]
Sorry for the delay, its finals week so I have been/will be super busy. Plan to address all PRs next Saturday.

**Comment by pacollins** [comment]
As with everything, its a moving target. [New Features for ML](https://gohugo.io/news/0.31-relnotes/)

**Comment by blgo** [comment]
I have noticed that flags are selected as default Facebook sharing images and made some custom changes to use og:image from the post field "featured". If this is not set for the page, it uses the logo image.

It might need some research on OpenGraph to diagnose this behaviour properly.

At the moment I am using this on the header.html file:


	{{ if and (isset .Params "featuredpath") (ne .Params.featuredpath "") }}
	    {{ $.Scratch.Set "path" .Params.featuredpath }}

	    {{ if and (isset .Params "featured") (ne .Params.featuredpath "") }}
		{{ $.Scratch.Set "structType" "page" }}
		{{ partial "img-path" . }}
		{{ $path := $.Scratch.Get "path" }}

		<meta property="og:image" 
			    content="{{ $path | relURL }}/{{ .Params.featured }}" />
	    {{ end }}

	{{ else }}
	<meta property="og:image" content="/img/main/logo.jpg" />
	
	{{ end }}

which will change the behaviour for sharing posts on Facebook but will have to be fixed before merging anyway.

Any suggestions?

**Comment by statnmap** [comment]
I do not think that the Multilingual MultiHost is a problem for the translation. I read it quickly, but everything is handled by Hugo. You just have to specify a baseURL for each language: https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost

**Comment by pacollins** [comment]
I am so far behind with staying up to date to this (thanks Teaching Practicum). Can anyone @statnmap or @blgo give me a quick status update?

Are all the templates updated for ML?
Is everything functional?
Is everything thematically coherent and aesthetically pleasing?
What is the status for its viability to merge?
Can we double back over to make sure the Merges just made aren't affected by this?

**Comment by blgo** [comment]
I have merged all my pull requests on top of statnmap's multilanguage branch and this is the result:
[https://demo-hugo-future-imperfect-multilanguage.netlify.com/](https://demo-hugo-future-imperfect-multilanguage.netlify.com/)

**Comment by statnmap** [comment]
@pacollins 
- Can you have a look at this one: https://github.com/statnmap/hugo-future-imperfect/pull/12
I am not sure about the translation of a dynamic variable. 
- For this PR https://github.com/statnmap/hugo-future-imperfect/pull/11, it would be nice to find a way to add the arrow near the flag but in a way that work for chrome as well. Neither @blgo nor me are comfortable enough with the css to do it nicely. Otherwise, this can be merged.

Once you have a look at these two PR, I would suggest to merge the multilanguage PR into the master, because all following modifications of your code may be different using the multilanguage. I think about relURl and relLangURL for instance. As well as some translations.

**Comment by statnmap** [comment]
@pacollins 
I merged all the pull requests of @blgo so that it is easier for you to see and test on my multilanguage branch directly.   
You can still have a look at these:

- Can you have a look at this one: statnmap#12
    I am not sure about the translation of a dynamic variable.
 -  For this PR statnmap#11, it would be nice to find a way to add the arrow near the flag but in a way that work for chrome as well. Neither @blgo nor me are comfortable enough with the css to do it nicely. Otherwise, this can be merged.

I think we may warn the template users that if they use custom taxonomies, they will have to add them in the i18n files like category/categories.

**Comment by pacollins** [comment]
@statnmap and @blgo Sorry, I have fallen behind on this. I will review this all this weekend.

Maybe we should look into an svg flag set that can be included with ML sites, but left out of regular sites? I have stumbled on [flag-icon-css](http://flag-icon-css.lip.is/) or [semantic-ui flags](https://semantic-ui.com/elements/flag.html) - just the css is located at `https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/components/flag.min.css`

**Comment by pacollins** [comment]
Sorry to double post. @statnmap, can you [change the base branch](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) of this PR to the new multilingual branch? I will be able to expedite its merge which will allow us to work on smaller chunks with more clarity which should help make the final push into the master.

**Comment by statnmap** [comment]
I think the project is mature enough to be merged, despite some minor previous comments.
And yes, working on a branch will be easier as we can define some specific issues and other PR.

**Pull request merged**
