### PR TITLE
Icon Style Tweak

### PR DESCRIPTION
**Pull request by BernCarney**
Updated social icon styles to be more consistant with the rest of the sidebar (centering icons by the footer, increase white space between icons and description param)

### CODE REVIEW

**Comment by pacollins** [comment]
Sorry for the delay, its finals week so I have been/will be super busy. Plan to address all PRs next Saturday.

**Comment by pacollins** [comment]
I see that you made more commits since I last commented - is this complete and ready to merge?

**Comment by BernCarney** [comment]
It is. I have more fixes in the works but wanted to wait until these PRs were merged to branch and work on those. Was actually planning on rebasing and creating a branch for each fix but these are small enough that it shouldn't matter. The other fixes are for staticman comments and a few other minor things

**Comment by BernCarney** [comment]
Down the road I'm actually looking to refactor the CSS and some code that isn't actually used anywhere if you want to make a refactor branch possibly. Just came across random snippets as I was customizing things.

**Comment by pacollins** [comment]
Yeah, I will go ahead and merge this.

The CSS is a mess because when it was ported originally, it just pulled everything from the HTML5Up File, even if it wasn't being used.

Thanks for the contribution!

**Pull request merged**
